spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: localhost:9092

  datasource:
    username: root
    url: jdbc:postgresql://localhost:5433/accounts
    password: secret
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'

topic:
  accounts:
    account-created: new_accounts_topic
    account-updated: update_accounts_topic
    account-deleted: delete_accounts_topic
  connections:
    new-following: new_following_topic
    friendship-unmade: friendship_unmade_topic

server:
  port: 8081
  error:
    include-message: always